### PR TITLE
I was trying the pr 

### LINKED ISSUE #11: Sales by Match
Resolve problem[ Sales by Match](https://www.hackerrank.com/challenges/sock-merchant/problem)

### PR DESCRIPTION
**Pull request by EleonoraDellamico**
It's a pr attempt just because my pc didn't recognize the file snackCase. Sorry for bothering I' going to update my branch with solutions in a while.

### CODE REVIEW

**Comment by EleonoraDellamico** [comment]
I changed the function snackCaseString and used the function split. Split cuts the array into a new one but doesn't pass the Javascript test.

**Comment by ferminhg** [comment]
Hi @EleonoraDellamico 👋 
Could you roll back your changes on `hackerank/js-practice/snakeCase.js` and add your `js-practice/Sales-by-Match.js ` in this PR?

That will leave Lucia's snakeCase solution in the repository, and we can work with the Sales by Match problem. 

Thanks !!!

**Comment by EleonoraDellamico** [comment]
@ferminhg Hi Fermín, I added js-practice/Sales-by-Match.js, please let me know if I did the pr properly, I have some doubts. 
About the snakeCase.js I think I did it.

**Comment by EleonoraDellamico** [comment]
Hi Fermín,
I'm really sorry I get in trouble with the pull request, and while I was
doing the merge in the snackCase.js I think I have also merged to the main
branch the new file match-sale.js for this reason the issue doesn`t appear
anymore.

Can I figure out it?
My apologies!

**Comment by ferminhg** [comment]
You did it great !!! 👍  
We are here to learn and practice, don't apologize 😆

When you have done this 100 times, you will realize how to avoid that trouble. Tomorrow we can review what happened to you if you needed it, although you resolved it very well, congrats !!!

**Comment by EleonoraDellamico** [comment]
Thank you Fermín 😌,

I have also figured out the first part of the problem:" Grading student", I
have created a new branch. On the other hand, I'm trying to understand the
other exercise "Day of the programmer" I saw the solution I think I  get it
but I have to go over the code in order to explain you in the best
possible way.

Thank you for your time, see you this afternoon.

**Pull request merged**
